### ISSUE TITLE
프로젝트 생성 및 설정

### ISSUE THREAD

**Issue by choi-ys** [learned-records/msa-shop#1]
# 개요
MSA 아키텍처 기반의 주문 프로젝트 구현을 위해 상품, 주문, 인증 등 주문 서비스 제공을 위해 필요한 각 도메인을 멀티 모듈 형태로 구성하고, 모듈 구현 및 구동에 필요한 의존성 및 환경 설정을 구성합니다.

# 목표
- 멀티 모듈 프로젝트 설정
- 각 모듈 구현에 필요한 의존성 추가
- 각 모듈 구동에 필요한 환경 설정 구성
- 각 모듈의 공통 설정 부를 별도 모듈로 추출

# TODO
- [ ] Root 프로젝트 설정
  - [ ] kotlin 실행 환경 구성
  - [ ] kotest 실행 환경 구성(intellij kotest plugin 설치)
- [ ] root 프로젝트 의존성 설정
  - [ ] root project boot jar 옵션 false 설정
  - [ ] sub project boot jar 옵션 true 설정
  - [ ] sub project plane jar 옵션 flase 설정

- [ ] 공통 모듈 생성 및 의존성 설정
- [ ] 상품 모듈 생성 및 의존성 설정
- [ ] 주문 모듈 생성 및 의존성 설정
- [ ] 인증 모듈 생성 및 의존성 설정
- [ ] 각 모듈 Test profile의 application.properties 구성
  - [ ] h2 MySQL 모드 환경 구성
  - [ ] jpa

---
분리된 주문, 상품 모듈간의 결합을 간접 참조로 변경
